#!/usr/bin/env bash

RETRYS=10
DELAY=1

cd ..

make app=WRO2023
if [ $? -eq 0 ]; then
    echo "Created app successfully"
else
    echo "Creating app failed"
    exit 1
fi

for i in $(seq 1 $RETRYS); do
    make upload
    if [ $? -eq 0 ]; then
        echo "Upload success"
        exit 0
    else
        echo "Upload failed"
    fi
    sleep $DELAY
done
